### ISSUE TITLE
Parallel converter sometimes fails "NoneType is not callable"

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-converters#9]
For some files (e.g. the `CEDAR_HISCO_se.csv` file) the parallel converter throws an exception "NoneType is not callable", this can be tested using the `tests.TestConversion.test_parallel_csvw_conversion_CEDAR` unittest e.g. : 

```
(clariah-converters) hoekstra@MB-033068:~/projects/clariah-converters/src$ python -m unittest tests.TestConversion.test_parallel_csvw_conversion_CEDAR
No handlers could be found for logger "rdflib.term"
Quotechar: '"'
Delimiter: ';'
Encoding : 'iso-8859-1'
Only taking encoding, quotechar and delimiter specifications into account...
Starting conversion
Opening CSV file for reading
Starting parsing process
Running with 2 processes
Traceback (most recent call last):
  File "converter/csvw.py", line 235, in _parallel
    for out in pool.imap(burstConvert_partial, enumerate(grouper(self._chunksize, reader))):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
TypeError: 'NoneType' object is not callable
```

Looked into various potential reasons, but to no avail. Might be a bug in the Python 2.7 multiprocessing module.

**Comment by RinkeHoekstra** [comment]
Current workaround: use a serial converter (i.e. processes=1) for files where this happens.
